export default function UserProfile() {
  return (
    <>
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-2">
        <div>
          <h2 className="font-display-lg text-display-lg text-on-surface text-glow">Your Profile</h2>
          <p className="font-body-md text-body-md text-on-surface-variant mt-2">Manage your career assets and VectorPath targeting.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-stack-md">
        
        {/* Left Column: Core Assets */}
        <div className="lg:col-span-8 flex flex-col gap-stack-md">
          
          {/* Active Job Profile & Upload */}
          <div className="glass-panel rounded-xl p-6 glow-cyan border-cyan-top relative overflow-hidden">
            <div className="flex justify-between items-start mb-6">
              <div>
                <h3 className="font-headline-md text-headline-md text-white mb-1">Target Job Profile</h3>
                <p className="font-body-md text-on-surface-variant">VectorPath is currently applying for these roles on your behalf.</p>
              </div>
              <span className="px-3 py-1 bg-primary-fixed-dim/20 text-primary-fixed-dim border border-primary-fixed-dim/30 rounded-full font-label-sm text-label-sm flex items-center gap-1">
                <span className="material-symbols-outlined text-sm">rocket_launch</span> Active
              </span>
            </div>
            
            <div className="bg-surface-container-low p-4 rounded-lg border border-white/5 flex flex-wrap gap-2 mb-6">
              <span className="px-3 py-1.5 bg-surface-variant rounded-md text-sm text-on-surface-variant">Senior Frontend Engineer</span>
              <span className="px-3 py-1.5 bg-surface-variant rounded-md text-sm text-on-surface-variant">Full Stack Developer</span>
              <span className="px-3 py-1.5 bg-surface-variant rounded-md text-sm text-on-surface-variant">UI/UX Engineer</span>
              <button className="px-3 py-1.5 bg-transparent border border-dashed border-outline text-on-surface-variant rounded-md text-sm hover:border-primary-fixed hover:text-primary-fixed transition-colors flex items-center gap-1">
                <span className="material-symbols-outlined text-sm">add</span> Add Role
              </button>
            </div>

            <h4 className="font-label-md text-label-md text-white mb-3">Resume & Cover Letter</h4>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="border border-white/10 rounded-lg p-4 flex items-center justify-between hover:bg-white/5 transition-colors cursor-pointer group">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-error/20 text-error flex items-center justify-center">
                    <span className="material-symbols-outlined">picture_as_pdf</span>
                  </div>
                  <div>
                    <p className="font-label-md text-white">Naren_Resume_2026.pdf</p>
                    <p className="font-label-sm text-on-surface-variant">Uploaded 2 days ago</p>
                  </div>
                </div>
                <span className="material-symbols-outlined text-on-surface-variant group-hover:text-white">upload</span>
              </div>
              
              <div className="border border-white/10 rounded-lg p-4 flex items-center justify-between hover:bg-white/5 transition-colors cursor-pointer group">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-primary/20 text-primary flex items-center justify-center">
                    <span className="material-symbols-outlined">description</span>
                  </div>
                  <div>
                    <p className="font-label-md text-white">Standard_Cover_Tech.txt</p>
                    <p className="font-label-sm text-on-surface-variant">Auto-generated by Agent</p>
                  </div>
                </div>
                <span className="material-symbols-outlined text-on-surface-variant group-hover:text-white">edit</span>
              </div>
            </div>
          </div>

          {/* Mapped Skills */}
          <div className="glass-panel rounded-xl p-6 border border-white/5">
            <div className="flex items-center gap-2 mb-4">
              <span className="material-symbols-outlined text-secondary-fixed-dim">troubleshoot</span>
              <h3 className="font-headline-md text-headline-md text-white">Mapped Skills</h3>
            </div>
            <p className="font-body-md text-on-surface-variant mb-6">These skills have been extracted from your resume and embedded into the vector matrix.</p>
            
            <div className="flex flex-wrap gap-2">
              {["React", "Next.js", "TypeScript", "Tailwind CSS", "Node.js", "Python", "FastAPI", "PostgreSQL", "LangGraph", "UI/UX Design", "Figma", "Git"].map((skill) => (
                <span key={skill} className="px-3 py-1 bg-secondary-container/20 border border-secondary-container/50 text-secondary-fixed rounded-full text-sm">
                  {skill}
                </span>
              ))}
            </div>
          </div>
          
        </div>

        {/* Right Column: AI Suggestions */}
        <div className="lg:col-span-4 flex flex-col gap-stack-md">
          <div className="glass-panel rounded-xl p-6 border-violet-top glow-violet">
            <div className="flex items-center gap-2 mb-4">
              <span className="material-symbols-outlined text-secondary-fixed-dim">psychology</span>
              <h3 className="font-headline-md text-headline-md text-white">Skill Suggestions</h3>
            </div>
            <p className="font-body-md text-on-surface-variant mb-6">Based on your target roles, acquiring these skills will increase your match probability by up to 18%.</p>
            
            <div className="space-y-4">
              <div className="bg-surface-container-high p-4 rounded-lg border border-white/5">
                <div className="flex justify-between items-start mb-2">
                  <h4 className="font-label-md text-white">Docker & Kubernetes</h4>
                  <span className="text-xs text-primary-fixed-dim bg-primary-fixed-dim/10 px-2 py-0.5 rounded">High Impact</span>
                </div>
                <p className="text-xs text-on-surface-variant mb-3">Appears in 68% of Senior Frontend job descriptions you match with.</p>
                <div className="w-full bg-surface-variant rounded-full h-1.5">
                  <div className="bg-primary-fixed-dim h-1.5 rounded-full" style={{ width: '15%' }}></div>
                </div>
                <p className="text-[10px] text-on-surface-variant mt-1 text-right">15% Proficiency Detected</p>
              </div>

              <div className="bg-surface-container-high p-4 rounded-lg border border-white/5">
                <div className="flex justify-between items-start mb-2">
                  <h4 className="font-label-md text-white">GraphQL</h4>
                  <span className="text-xs text-secondary-fixed-dim bg-secondary-fixed-dim/10 px-2 py-0.5 rounded">Medium Impact</span>
                </div>
                <p className="text-xs text-on-surface-variant mb-3">Frequently paired with React and Next.js in your target tier.</p>
                <div className="w-full bg-surface-variant rounded-full h-1.5">
                  <div className="bg-secondary-fixed-dim h-1.5 rounded-full" style={{ width: '40%' }}></div>
                </div>
                <p className="text-[10px] text-on-surface-variant mt-1 text-right">40% Proficiency Detected</p>
              </div>

              <div className="bg-surface-container-high p-4 rounded-lg border border-white/5">
                <div className="flex justify-between items-start mb-2">
                  <h4 className="font-label-md text-white">WebGL / Three.js</h4>
                  <span className="text-xs text-secondary-fixed-dim bg-secondary-fixed-dim/10 px-2 py-0.5 rounded">Niche Boost</span>
                </div>
                <p className="text-xs text-on-surface-variant mb-3">Unlocks Tier 1 creative development roles.</p>
                <button className="w-full py-2 bg-surface-variant hover:bg-white/10 text-on-surface-variant text-xs rounded transition-colors mt-2">
                  View Recommended Courses
                </button>
              </div>
            </div>
          </div>
        </div>

      </div>
    </>
  );
}
